name: binary_data
description: Library for manipulating bytes in memory.
version: 0.5.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: any

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
